services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
      no_cache: true
    ports:
      - "8082:8082"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      no_cache: true
    ports:
      - "8081:8081"
    restart: unless-stopped