services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_URL=
      - DB_USER=
      - DB_PASSWORD=
      - MQTT_BROKER=
      - MQTT_TOPIC1=
      - MQTT_TOPIC2=
      - SERVER_PORT=
      - SERVER_CONTEXT_PATH=
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:8080"
    restart: unless-stopped