#Configuracion MQTT
MQTT_BROKER = tcp://<ip-broker>:1883
MQTT_TOPIC1 =
MQTT_TOPIC2 =
MQTT_QOS = 0
#Configuracion DB
DB_URL =
DB_USER =
DB_PASSWORD =
#Configuracion API REST
BACKEND_PORT =
BACKEND_IP = 0.0.0.0
BACKEND_CONTEXT_PATH =