#Configuración MQTT
MQTT_BROKER = tcp://186.182.43.39:1883
MQTT_TOPIC1 = tempyhum
MQTT_TOPIC2 = luz
#Configuración DB
DB_URL = jdbc:postgresql://186.182.43.39:5432/basededatos
DB_USER = totty
DB_PASSWORD = tomas3342
#Configuración API REST
SERVER_PORT = 8082
SERVER_IP = 0.0.0.0
SERVER_CONTEXT_PATH =

