IP_ADDRESS = host.docker.internal
#Configuración MQTT
MQTT_BROKER = tcp://host.docker.internal:1883
MQTT_TOPIC1 = tempyhum
MQTT_TOPIC2 = luz
#Configuración DB
DB_URL = jdbc:postgresql://host.docker.internal:5432/basededatos
DB_USER =
DB_PASSWORD = 
#Configuración API REST
SERVER_PORT = 8080
SERVER_IP = 0.0.0.0
SERVER_CONTEXT_PATH =

